FROM node:20-alpine
WORKDIR /app

# tools sometimes needed for native deps
RUN apk add --no-cache bash python3 make g++

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 3333
CMD ["npm","run","dev"]
